name: ZMK Firmware

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */2 *' # run every two months to keep artifacts from expiring

jobs:
  convert-and-store-keymap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Convert keymap or use raw DTS
        run: |
          if [ -f "scripts/convert_keymap.py" ]; then
            python scripts/convert_keymap.py -c q2c --in-path "$GITHUB_WORKSPACE/config/charybdis.keymap" || echo "Conversion failed, using raw DTS"
          fi
          cp "$GITHUB_WORKSPACE/config/charybdis.keymap" "$GITHUB_WORKSPACE/config/charybdis_converted.keymap"
      - uses: actions/upload-artifact@v4
        with:
          name: keymap_files
          path: ${{ github.workspace }}/config/*.keymap

  build:
    needs: convert-and-store-keymap
    uses: ./.github/workflows/user_config_build.yaml
    # Fallback: If the issue persists, comment out the above line and use a manual build step
    # - run: |
    #     echo "Manual build fallback"
    #     docker run --rm -v $(pwd):/work zmkfirmware/zmk-build-arm:stable west build --pristine -s zmk/app -b nice_nano_v2 -DSHIELD=charybdis_left
