name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - board: nice_nano_v2
            shield: charybdis_left
            keymap: qwerty
            format: bt
            artifact-name: charybdis_qwerty_left
          - board: nice_nano_v2
            shield: charybdis_right
            keymap: qwerty
            format: bt
            artifact-name: charybdis_qwerty_right
            snippet: studio-rpc-usb-uart
          - board: nice_nano_v2
            shield: settings_reset
            format: reset
            artifact-name: firmware_reset_nano_v2
    steps:
      - uses: actions/checkout@v3
      - name: Set up ZMK environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake ninja-build dfu-util
          pip3 install west
          west init -m https://github.com/zmkfirmware/zmk.git --mr feat/pointers-with-input-processors
          cd zmk
          west update
      - name: Build ZMK Firmware
        run: |
          cd zmk
          west build -b nice_nano_v2 -- -DSHIELD=${{ matrix.shield }} -DZMK_KEYMAP=${{ matrix.keymap }} -DFORMAT=${{ matrix.format }} -DARTIFACT_NAME=${{ matrix.artifact-name }} ${{ matrix.snippet && format('-DSNIPPET={0}', matrix.snippet) || '' }}
        env:
          WEST_OUTPUT: build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zmk-firmware
          path: zmk/build/zephyr/*.uf2
