- name: Copy config files to isolated temporary directory
  run: |
    if [ "${{ env.base_dir }}" != "${GITHUB_WORKSPACE}" ]; then
      apt-get -qq update && apt-get -q install -o Dpkg::Progress-Fancy="0" -o APT::Color="0" -o Dpkg::Use-Pty="0" tree
      
      # Define base directory for config
      base_config_path="${{ env.base_dir }}/${{ inputs.config_path }}"

      # Create config directory
      mkdir -p "$base_config_path"
      
      # Copy config files
      cp -R "${{ inputs.config_path }}"/* "$base_config_path/"
      echo "config files ready"
      
      # Copy keymap & physical layouts
      if [ "${{ env.shield }}" != "settings_reset" ]; then
        # Copy physical layout file to shield directory
        mv -v "$base_config_path/charybdis-layouts.dtsi" \
          "${GITHUB_WORKSPACE}/boards/shields/charybdis-${{ env.format }}/"

        # Copy active keymap to the board directory & adjust for bt/dongle format
        cp -Rv "$GITHUB_WORKSPACE/${{ inputs.keymap_path }}/${{ env.keymap }}.keymap" \
          "$base_config_path/charybdis.keymap"
        echo "format: ${{ env.format }}"
        case "${{ env.format }}" in
          *bt*)
            echo "converting trackball device to bt/usb format"
            # Precisely replace device only within trackball listener nodes
            sed -i '/trackball_\w*_listener\s*{/,/};/ s/device = <&vtrackball>;/device = <&trackball>;/' "$base_config_path/charybdis.keymap"
            # Verify the replacement
            if ! grep -q "device = <&trackball>;" "$base_config_path/charybdis.keymap"; then
              echo "Error: Replacement failed, using original keymap"
            else
              echo "Replacement successful"
            fi
            grep "device = <" "$base_config_path/charybdis.keymap"
            ;;
        esac
      fi
      
      # Remove untargeted shields so they don't get auto picked up by the west build command
      find "${GITHUB_WORKSPACE}/boards/shields" \
        -mindepth 1 \
        -maxdepth 1 \
        ! -name "charybdis-${{ env.format }}" \
        -exec rm -rf {} +
      echo "Removed extra shields"

      echo "Build files list:"
      tree "${{ env.base_dir }}"
      tree "${GITHUB_WORKSPACE}/boards/shields"
    fi
